// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Current Connection State Information
type ConnectionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Qr            *string                `protobuf:"bytes,3,opt,name=qr,proto3,oneof" json:"qr,omitempty"`
	PairingCode   *string                `protobuf:"bytes,4,opt,name=pairing_code,json=pairingCode,proto3,oneof" json:"pairing_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionUpdate) Reset() {
	*x = ConnectionUpdate{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionUpdate) ProtoMessage() {}

func (x *ConnectionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionUpdate.ProtoReflect.Descriptor instead.
func (*ConnectionUpdate) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionUpdate) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConnectionUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectionUpdate) GetQr() string {
	if x != nil && x.Qr != nil {
		return *x.Qr
	}
	return ""
}

func (x *ConnectionUpdate) GetPairingCode() string {
	if x != nil && x.PairingCode != nil {
		return *x.PairingCode
	}
	return ""
}

// Received Events from Worker
type WorkerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WorkerEvent_Connection
	//	*WorkerEvent_RawLog
	Event         isWorkerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerEvent) GetEvent() isWorkerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WorkerEvent) GetConnection() *ConnectionUpdate {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Connection); ok {
			return x.Connection
		}
	}
	return nil
}

func (x *WorkerEvent) GetRawLog() string {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_RawLog); ok {
			return x.RawLog
		}
	}
	return ""
}

type isWorkerEvent_Event interface {
	isWorkerEvent_Event()
}

type WorkerEvent_Connection struct {
	Connection *ConnectionUpdate `protobuf:"bytes,1,opt,name=connection,proto3,oneof"`
}

type WorkerEvent_RawLog struct {
	RawLog string `protobuf:"bytes,2,opt,name=raw_log,json=rawLog,proto3,oneof"`
}

func (*WorkerEvent_Connection) isWorkerEvent_Event() {}

func (*WorkerEvent_RawLog) isWorkerEvent_Event() {}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\bwhatsaly\"\x95\x01\n" +
	"\x10ConnectionUpdate\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x13\n" +
	"\x02qr\x18\x03 \x01(\tH\x00R\x02qr\x88\x01\x01\x12&\n" +
	"\fpairing_code\x18\x04 \x01(\tH\x01R\vpairingCode\x88\x01\x01B\x05\n" +
	"\x03_qrB\x0f\n" +
	"\r_pairing_code\"o\n" +
	"\vWorkerEvent\x12<\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x1a.whatsaly.ConnectionUpdateH\x00R\n" +
	"connection\x12\x19\n" +
	"\araw_log\x18\x02 \x01(\tH\x00R\x06rawLogB\a\n" +
	"\x05eventB%Z#github.com/astrox11/whatsaly/api/pbb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_events_proto_goTypes = []any{
	(*ConnectionUpdate)(nil), // 0: whatsaly.ConnectionUpdate
	(*WorkerEvent)(nil),      // 1: whatsaly.WorkerEvent
}
var file_proto_events_proto_depIdxs = []int32{
	0, // 0: whatsaly.WorkerEvent.connection:type_name -> whatsaly.ConnectionUpdate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	file_proto_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[1].OneofWrappers = []any{
		(*WorkerEvent_Connection)(nil),
		(*WorkerEvent_RawLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
